"""Convert an Avular Cerebra Studio map into a Gazebo world for the Origin One sim.

The containers use this through tools/cerebra_import.py, which reads the
shared cerebra-data/ folder at startup. Running this script directly is only
needed to inspect the generated files.

Cerebra Studio stores maps as JSON in
  %APPDATA%\\Avular\\Cerebra Studio\\Mission Planner\\maps\\{id}.json
with a base64 ROS-style occupancy grid (0 = free, 100 = occupied,
255 = unknown, row 0 at the map origin) and waypoints in ...\\waypoints\\.

Outputs in --out-dir:
  <name>.world   Gazebo Fortress world with waypoint markers
  <name>.obj     map walls extruded into one mesh (+ <name>.mtl)
  <name>.pgm     occupancy image (ROS map_server convention)
  <name>.yaml    map metadata for Nav2 / map_server
  <name>.env     settings to paste into docker-compose.yml

Only the Python standard library is needed.

Example:
  py tools/cerebra_map_to_world.py "%APPDATA%/Avular/Cerebra Studio/Mission Planner/maps/{id}.json" --name jmh_3rd_floor
"""

import argparse
import base64
import glob
import json
import math
import os
import re
import sys

FREE, OCCUPIED, UNKNOWN = 0, 100, 255
CONTAINER_MAPS_DIR = "/home/origin_ws/install/origin_one_gazebo/share/origin_one_gazebo/worlds/custom"


def load_map(path):
    with open(path, encoding="utf-8") as f:
        m = json.load(f)
    w = m["size"]["width_in_pixels"]
    h = m["size"]["height_in_pixels"]
    grid = base64.b64decode(m["occupancy_grid"])
    if len(grid) != w * h:
        sys.exit(f"Grid has {len(grid)} cells, expected {w}x{h}={w * h}")
    res = m["size"]["width_in_meters"] / w
    return m, grid, w, h, res


def load_waypoints(waypoint_dir, map_id):
    waypoints = []
    for path in sorted(glob.glob(os.path.join(waypoint_dir, "*.json"))):
        with open(path, encoding="utf-8") as f:
            wp = json.load(f)
        if wp.get("coordinate_system_info", {}).get("local_relative") != map_id:
            continue
        q = wp["pose"]["orientation"]
        yaw = math.atan2(2 * (q["w"] * q["z"] + q["x"] * q["y"]),
                         1 - 2 * (q["y"] ** 2 + q["z"] ** 2))
        p = wp["pose"]["position"]
        waypoints.append({"name": wp["name"], "x": p["x"], "y": p["y"], "yaw": yaw})
    return waypoints


def merge_walls(grid, w, h, threshold):
    """Greedily cover occupied cells with rectangles (col0, row0, col1, row1), inclusive."""
    todo = bytearray(1 if threshold <= v <= 100 else 0 for v in grid)
    rects = []
    for r in range(h):
        base = r * w
        for c in range(w):
            if not todo[base + c]:
                continue
            c1 = c
            while c1 + 1 < w and todo[base + c1 + 1]:
                c1 += 1
            r1 = r
            while r1 + 1 < h and all(todo[(r1 + 1) * w + cc] for cc in range(c, c1 + 1)):
                r1 += 1
            for rr in range(r, r1 + 1):
                todo[rr * w + c:rr * w + c1 + 1] = bytes(c1 - c + 1)
            rects.append((c, r, c1, r1))
    return rects


def write_obj(path, mtl_name, rects, res, origin, wall_height):
    """Write all wall boxes as one OBJ mesh.

    A single mesh is far cheaper for Gazebo than thousands of separate box
    visuals/collisions (those used ~15 GB RAM and ran at ~0.2x real time).
    Bottom faces are omitted because they rest on the floor.
    """
    ox, oy = origin["x"], origin["y"]
    zt = wall_height
    normals = "vn 0 0 1\nvn 1 0 0\nvn -1 0 0\nvn 0 1 0\nvn 0 -1 0\n"
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(f"# Generated by cerebra_map_to_world.py\nmtllib {mtl_name}\no map_walls\n{normals}usemtl wall\n")
        v = 0
        for c0, r0, c1, r1 in rects:
            x0, x1 = ox + c0 * res, ox + (c1 + 1) * res
            y0, y1 = oy + r0 * res, oy + (r1 + 1) * res
            f.write(f"v {x0:.3f} {y0:.3f} 0\nv {x1:.3f} {y0:.3f} 0\nv {x1:.3f} {y1:.3f} 0\nv {x0:.3f} {y1:.3f} 0\n"
                    f"v {x0:.3f} {y0:.3f} {zt:.3f}\nv {x1:.3f} {y0:.3f} {zt:.3f}\n"
                    f"v {x1:.3f} {y1:.3f} {zt:.3f}\nv {x0:.3f} {y1:.3f} {zt:.3f}\n")
            b = v + 1
            # top, +x, -x, +y, -y (counter-clockwise seen from outside)
            f.write(f"f {b+4}//1 {b+5}//1 {b+6}//1 {b+7}//1\n"
                    f"f {b+1}//2 {b+2}//2 {b+6}//2 {b+5}//2\n"
                    f"f {b+3}//3 {b+0}//3 {b+4}//3 {b+7}//3\n"
                    f"f {b+2}//4 {b+3}//4 {b+7}//4 {b+6}//4\n"
                    f"f {b+0}//5 {b+1}//5 {b+5}//5 {b+4}//5\n")
            v += 8
    with open(os.path.join(os.path.dirname(path), mtl_name), "w", encoding="utf-8", newline="\n") as f:
        f.write("newmtl wall\nKa 0.75 0.75 0.72\nKd 0.75 0.75 0.72\nKs 0.1 0.1 0.1\nd 1.0\n")


def write_pgm(path, grid, w, h):
    # map_server images have the top row at max y, so rows are flipped.
    shade = {FREE: 254, OCCUPIED: 0}
    with open(path, "wb") as f:
        f.write(f"P5\n{w} {h}\n255\n".encode())
        for r in range(h - 1, -1, -1):
            f.write(bytes(shade.get(v, 0 if 50 <= v <= 100 else 205)
                          for v in grid[r * w:(r + 1) * w]))


def write_yaml(path, pgm_name, res, origin):
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"image: {pgm_name}\nmode: trinary\nresolution: {res:.6f}\n"
                f"origin: [{origin['x']:.6f}, {origin['y']:.6f}, 0.0]\n"
                "negate: 0\noccupied_thresh: 0.65\nfree_thresh: 0.25\n")


def world_sdf(m, n_rects, res, waypoints, spawn, wall_height, mesh_uri):
    ltp = m["global_reference_frame"]["local_tangent_plane"]
    mesh = f"<geometry><mesh><uri>{mesh_uri}</uri></mesh></geometry>"

    markers = []
    for wp in waypoints:
        safe = re.sub(r"[^A-Za-z0-9_]", "_", wp["name"])
        markers.append(f"""
    <!-- Waypoint "{wp['name']}" (visual only, no collision) -->
    <model name='waypoint_{safe}'>
      <static>1</static>
      <pose>{wp['x']:.3f} {wp['y']:.3f} 0.002 0 0 {wp['yaw']:.4f}</pose>
      <link name='link'>
        <visual name='disc'>
          <geometry><cylinder><radius>0.3</radius><length>0.004</length></cylinder></geometry>
          <material><ambient>0.1 0.8 0.2 1</ambient><diffuse>0.1 0.8 0.2 1</diffuse></material>
        </visual>
        <visual name='heading'>
          <pose>0.35 0 0 0 0 0</pose>
          <geometry><box><size>0.3 0.06 0.006</size></box></geometry>
          <material><ambient>0.1 0.8 0.2 1</ambient><diffuse>0.1 0.8 0.2 1</diffuse></material>
        </visual>
      </link>
    </model>""")

    return f"""<?xml version='1.0'?>
<!-- Generated by tools/cerebra_map_to_world.py from Cerebra Studio map "{m['name']}" ({m['id']}) -->
<sdf version='1.6'>
  <world name='default'>
    <spherical_coordinates>
      <surface_model>EARTH_WGS84</surface_model>
      <world_frame_orientation>ENU</world_frame_orientation>
      <latitude_deg>{ltp['latitude']}</latitude_deg>
      <longitude_deg>{ltp['longitude']}</longitude_deg>
      <elevation>{ltp['altitude']}</elevation>
      <heading_deg>0</heading_deg>
    </spherical_coordinates>

    <physics name='1ms' type='ignored'>
      <max_step_size>0.01</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin filename='ignition-gazebo-physics-system' name='gz::sim::systems::Physics'/>
    <plugin filename='ignition-gazebo-scene-broadcaster-system' name='gz::sim::systems::SceneBroadcaster'/>
    <plugin filename='ignition-gazebo-user-commands-system' name='ignition::gazebo::systems::UserCommands'/>

    <light name='sun' type='directional'>
      <cast_shadows>0</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.8 0.8 0.8 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <direction>0.5 0.1 -0.9</direction>
    </light>

    <scene>
      <ambient>0.5 0.5 0.5 1</ambient>
      <background>0.7 0.7 0.7 1</background>
      <shadows>0</shadows>
    </scene>

    <gui fullscreen='0'>
      <camera name='user_camera'>
        <pose>{spawn['x']:.2f} {spawn['y'] - 6:.2f} 8 0 0.9 1.5707</pose>
        <view_controller>orbit</view_controller>
      </camera>
    </gui>

    <model name='ground_plane'>
      <static>1</static>
      <link name='link'>
        <collision name='collision'>
          <geometry><plane><normal>0 0 1</normal><size>300 300</size></plane></geometry>
          <surface><friction><ode><mu>100</mu><mu2>50</mu2></ode></friction></surface>
        </collision>
        <visual name='visual'>
          <cast_shadows>0</cast_shadows>
          <geometry><plane><normal>0 0 1</normal><size>300 300</size></plane></geometry>
          <material><ambient>0.45 0.45 0.45 1</ambient><diffuse>0.45 0.45 0.45 1</diffuse></material>
        </visual>
      </link>
    </model>

    <!-- Walls of {m['name']}: {n_rects} merged boxes in one mesh ({res:.3f} m/cell, {wall_height} m high) -->
    <model name='map_walls'>
      <static>1</static>
      <link name='link'>
        <collision name='collision'>{mesh}</collision>
        <visual name='visual'>{mesh}</visual>
      </link>
    </model>
{''.join(markers)}
  </world>
</sdf>
"""


def free_near(grid, w, h, res, origin, x, y, radius_m=0.4):
    c = int((x - origin["x"]) / res)
    r = int((y - origin["y"]) / res)
    n = int(radius_m / res)
    for dr in range(-n, n + 1):
        for dc in range(-n, n + 1):
            rr, cc = r + dr, c + dc
            if 0 <= rr < h and 0 <= cc < w and 50 <= grid[rr * w + cc] <= 100:
                return False
    return 0 <= r < h and 0 <= c < w


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("map_json", help="Cerebra Studio map file (maps/{id}.json)")
    ap.add_argument("--name", help="output base name (default: from the map name)")
    ap.add_argument("--out-dir", default=os.path.join(os.path.dirname(__file__), "..", "maps"))
    ap.add_argument("--waypoints-dir", help="default: ../waypoints next to the maps folder")
    ap.add_argument("--spawn", default="Home", help="waypoint name to spawn the robot at")
    ap.add_argument("--wall-height", type=float, default=2.0)
    ap.add_argument("--occupied-threshold", type=int, default=65,
                    help="cells with value >= this (and <= 100) become walls")
    ap.add_argument("--mesh-dir", default=CONTAINER_MAPS_DIR,
                    help="folder where ./maps is mounted inside the sim container")
    args = ap.parse_args()

    m, grid, w, h, res = load_map(args.map_json)
    name = args.name or re.sub(r"[^a-z0-9]+", "_", m["name"].lower()).strip("_")
    wp_dir = args.waypoints_dir or os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(args.map_json))), "waypoints")
    waypoints = load_waypoints(wp_dir, m["id"]) if os.path.isdir(wp_dir) else []

    spawn = next((wp for wp in waypoints if wp["name"] == args.spawn), None)
    if spawn is None:
        print(f"Waypoint '{args.spawn}' not found for this map; spawning at (0, 0).")
        spawn = {"name": "origin", "x": 0.0, "y": 0.0, "yaw": 0.0}
    if not free_near(grid, w, h, res, m["origin"], spawn["x"], spawn["y"]):
        print(f"WARNING: spawn point ({spawn['x']:.2f}, {spawn['y']:.2f}) is within 0.4 m of a wall.")

    rects = merge_walls(grid, w, h, args.occupied_threshold)
    os.makedirs(args.out_dir, exist_ok=True)
    out = lambda ext: os.path.join(args.out_dir, name + ext)

    write_obj(out(".obj"), name + ".mtl", rects, res, m["origin"], args.wall_height)
    # The sim launch file overwrites Gazebo's resource path, so the mesh is
    # referenced by its absolute path inside the container.
    mesh_uri = "file://" + args.mesh_dir.rstrip("/") + f"/{name}.obj"
    with open(out(".world"), "w", encoding="utf-8", newline="\n") as f:
        f.write(world_sdf(m, len(rects), res, waypoints, spawn, args.wall_height, mesh_uri))
    write_pgm(out(".pgm"), grid, w, h)
    write_yaml(out(".yaml"), name + ".pgm", res, m["origin"])
    env = (f"SIM_WORLD=custom/{name}.world\n"
           f"ROBOT_POSE_X={spawn['x']:.3f}\nROBOT_POSE_Y={spawn['y']:.3f}\nROBOT_POSE_YAW={spawn['yaw']:.4f}\n")
    with open(out(".env"), "w", encoding="utf-8", newline="\n") as f:
        f.write(env)

    print(f"Map '{m['name']}': {w}x{h} cells at {res:.3f} m, {len(rects)} wall boxes, "
          f"{len(waypoints)} waypoint(s): {', '.join(wp['name'] for wp in waypoints) or '-'}")
    print(f"Spawn at '{spawn['name']}': x={spawn['x']:.3f} y={spawn['y']:.3f} yaw={spawn['yaw']:.4f}")
    print(f"Wrote {out('.world')}, .obj, .mtl, .pgm, .yaml, .env")
    print("Use it: copy the .env values into docker-compose.yml (or Simulation-Docker/.env)"
          " and run `docker compose up -d avular-origin-sim`.")


if __name__ == "__main__":
    main()
